Works
lu-jim/mobile-portfolio pull request #2
Opened 2021-09-22 20:50 UTC by lu-jim

## Second PR for this project
- Add Works section using CSS Grid
- Add About section

2021-09-22 22:57 UTC, Alexoid1 requested changes
# Hi @lu-jim,

Impressive project!
You are doing a great job so far, and the project is looking good.
- No linter errors
- Follow Github-flow guidelines.
- Descriptive README.md file.
- Impressive project is almost the exact same design as the Figma template.

## Required Changes :recycle:
 - For the project to get approved, also implement the changes mentioned below.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-09-22 22:57 UTC, Alexoid1 commented on index.html
> +        </div>
- [ ] Kindly replace `div` with `ul` tag and list the technologies with `li` tags.

2021-09-22 22:57 UTC, Alexoid1 commented on index.html
> +        </div>
- [ ] Kindly replace `div` with `ul` tag and list the technologies with `li` tags.

2021-09-22 22:57 UTC, Alexoid1 commented on index.html
> +        </div>
- [ ] Kindly replace `div` with `ul` tag and list the technologies with `li` tags.

2021-09-22 22:57 UTC, Alexoid1 commented on index.html
> +        </div>
- [ ] Kindly replace div with ul tag and list the technologies with li tags.

2021-09-22 22:57 UTC, Alexoid1 commented on index.html
> +      <article class="card card-1">
- [ ] Kindly make the image and paragraph responsive for mobile devices.
![Captura de pantalla_2021-09-22_17-19-38](https://user-images.githubusercontent.com/53111464/134430626-7e05a266-bee3-4334-badb-cef595683d48.png)

2021-09-22 22:57 UTC, Alexoid1 commented on index.html
> +      <article class="card card-2">
- [ ] Kindly make the image and paragraph responsive for mobile devices.
![Captura de pantalla_2021-09-22_17-19-56](https://user-images.githubusercontent.com/53111464/134430893-d06e2726-db0a-4a76-85e5-f2b62a53d1ea.png)

2021-09-22 22:57 UTC, Alexoid1 commented on index.html
> +      <article class="card card-3">
- [ ] Kindly make the image and paragraph responsive for mobile devices.
![Captura de pantalla_2021-09-22_17-20-16](https://user-images.githubusercontent.com/53111464/134430976-0df22f42-3193-4110-984f-1a92f4aec4c7.png)

2021-09-22 22:57 UTC, Alexoid1 commented on index.html
> +      <article class="card card-4">
- [ ] Kindly make the image and paragraph responsive for mobile devices.

2021-09-22 22:57 UTC, Alexoid1 commented on index.html
> +      <h2 class="about-title title">
- [ ] Kindly fix the styles in the about section, the paragraph is not responsive for mobile devices.
- [ ] Kindly add margin to the section container.
- [ ] Make the containers of every technology responsive for mobile devices.
![Captura de pantalla_2021-09-22_17-48-40](https://user-images.githubusercontent.com/53111464/134432109-cfdedc9b-eb89-4be9-a811-cbabf62a88c7.png)

2021-09-22 22:57 UTC, Alexoid1 commented on index.html
>            <p class="descr">I’m a software developer! I can help you build a product, feature or website. Look through
-[OPTIONAL] Kindly add some margin to this section and make the paragraph responsive for mobile devices.
![Captura de pantalla_2021-09-22_17-56-19](https://user-images.githubusercontent.com/53111464/134432709-fdc9d266-446d-4dfa-bf3f-cd1f25576bca.png)

2021-09-23 15:58 UTC, carlos-ssh approved these changes
hi @lu-jim , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-23 16:42 UTC, merged